name: Build and publish container

inputs:
  version:
    required: true
    type: string
  publish:
    default: false
    type: boolean
  github_token:
    required: true

runs:
  using: "composite"
  steps:
    # Login against a container registry
    # https://github.com/docker/login-action
    - name: Log into registry ${{ env.REGISTRY }}
      if: inputs.publish
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ inputs.github_token }}

    # Extract metadata (tags, labels) for the container
    # https://github.com/docker/metadata-action
    - name: Extract container metadata
      id: meta
      uses: docker/metadata-action@v5
      with:
        images: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}
        tags: |
          type=semver,pattern={{version}},value=${{ inputs.version }}
          type=semver,pattern={{major}}.{{minor}},value=${{ inputs.version }}
          type=raw,value=latest,enable=false
        labels: |
          org.opencontainers.image.licenses=GPL-2.0-or-later
          org.opencontainers.image.description=Blender CPU image

    # Build and push image with Buildx
    # https://github.com/docker/build-push-action
    - name: Build and push container image
      id: build-and-push
      uses: docker/build-push-action@v5
      with:
        build-args: |
          BLENDER_VERSION=${{ steps.meta.outputs.version }}
        context: .
        push: ${{ inputs.publish }}
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
